#!/usr/bin/env sh

#
# for this to work you must configure sudo such that
# it will be able to run the command without password
#
# see this wiki page for information:
#  - https://github.com/koekeishiya/yabai/wiki/Installing-yabai-(latest-release)#configure-scripting-addition
#
# yabai -m signal --add event=dock_did_restart action="sudo yabai --load-sa"
# sudo yabai --load-sa
#

# global settings
yabai -m config                                       \
    mouse_follows_focus          off                  \
    focus_follows_mouse          off                  \
    window_origin_display        default              \
    window_placement             second_child         \
    window_topmost               on                   \
    window_shadow                off                  \
    window_animation_duration    0.0                  \
    window_opacity_duration      0.0                  \
    active_window_opacity        0.4                  \
    normal_window_opacity        1.0                  \
    window_opacity               off                  \
    insert_feedback_color        0xffd75f5f           \
    active_window_border_color   0xffadd827           \
    normal_window_border_color   0xff555555           \
    window_border_width          1                    \
    window_border_radius         12                   \
    window_border_blur           off                  \
    window_border_hidpi          on                   \
    window_border                on                   \
    split_ratio                  0.50                 \
    split_type                   auto                 \
    auto_balance                 off                  \
    top_padding                  42                   \
    bottom_padding               12                   \
    left_padding                 12                   \
    right_padding                12                   \
    window_gap                   06                   \
    layout                       bsp                  \
    mouse_modifier               fn                   \
    mouse_action1                move                 \
    mouse_action2                resize               \
    mouse_drop_action            swap                 

# Running through float windows
yabai -m space 1 --label web
yabai -m space 2 --label code
yabai -m space 3 --label terminal
yabai -m space 4 --label SQL
yabai -m space 5 --label chat
yabai -m space 6 --label music

# Rules for specific apps to launch and be managed by yabai
yabai -m rule --add app=Spotify --space 6
yabai -m rule --add app=Discord --space 6
yabai -m rule --add app="^System Preferences$" manage=off
yabai -m rule --add app="^Системные настройки$" manage=off
yabai -m rule --add app="System Preferences" manage=off
yabai -m rule --add app="Системные настройки" manage=off
yabai -m rule --add app=Dashlane manage=off
yabai -m rule --add app=Spotify manage=off
yabai -m rule --add app=Godot manage=off
yabai -m rule --add app=Discord manage=off
yabai -m rule --add app=Übersicht manage=off
yabai -m rule --add app=BetterTouchTool manage=off

echo "yabai configuration loaded.."
