#!/usr/bin/env sh

# Color Palette
COLOR_CHARADE=0xff1e1f29
COLOR_TUNA=0xff343647
COLOR_SPRING_WOOD=0xfff6f7ee
COLOR_MALIBU=0xff7ce3fd
COLOR_HONEYSUCKLE=0xffeefd79
COLOR_HOT_PINK=0xfffc5dba
COLOR_AMARANTH=0xffec3a43
COLOR_HELIOTROPE=0xffac7af7
COLOR_CHATEAU_GREEN=0xff3dbf58
COLOR_RED=0xffff0019

# General Bar
BAR_COLOR=$COLOR_CHARADE

# Widget Spaces
SPACE_COLOR=$COLOR_SPRING_WOOD
SPACE_BACKGROUND=$COLOR_TUNA
SPACE_COLOR_ACTIVE=$COLOR_TUNA
SPACE_BACKGROUND_ACTIVE=$COLOR_SPRING_WOOD

# Widget Date
DATE_COLOR=$COLOR_MALIBU

# Widget Time
TIME_COLOR=$COLOR_HONEYSUCKLE

# Widget Keyboard
KEYBOARD_COLOR=$COLOR_HOT_PINK

# Widget Wifi
WIFI_COLOR=$COLOR_AMARANTH

# Widget Volume
VOLUME_COLOR=$COLOR_HELIOTROPE

# Wiget Battery
BATTERY_CHARGE_COLOR=$COLOR_CHATEAU_GREEN
BATTERY_DISCHARGED_COLOR=$COLOR_RED

# Widget Memory
MEMORY_COLOR=$COLOR_CHATEAU_GREEN
MEMORY_DANGER_COLOR=$COLOR_RED

# Widget CPU
CPU_COLOR=$COLOR_CHATEAU_GREEN
CPU_DANGER_COLOR=$COLOR_RED