#!/usr/bin/env sh

# Load Colors
source "$HOME/.config/sketchybar/colors.sh"

# Load Icons
source "$HOME/.config/sketchybar/icons.sh"

# Widgets Directory
WIDGETS_DIR="$HOME/.config/sketchybar/widgets"

# Plugins Directory
PLUGINS_DIR="$HOME/.config/sketchybar/plugins"

# Base Font
FONT="JetBrainsMono Nerd Font Mono"

# Setting up the general bar appearance and default values
sketchybar  --bar     height=34                          \
                      color=$BAR_COLOR                   \
                      shadow=off                         \
                      position=top                       \
                      sticky=on                          \
                      padding_right=4                    \
                      padding_left=4                     \
                      corner_radius=0                    \
                      y_offset=0                         \
                      margin=0                           \
                      notch_width=200                    \
                                                         \
            --default updates=when_shown                 \
                      icon.font="$FONT:SemiBold:13.0"    \
                      icon.color=$ICON_COLOR             \
                      icon.padding_left=10               \
                      icon.padding_right=6               \
                      label.font="$FONT:Bold:12.0"       \
                      label.color=$LABEL_COLOR           \
                      label.padding_left=4               \
                      label.padding_right=10             \
                      background.padding_right=4         \
                      background.padding_left=4

# Widgets on the Left
function left_widgets() {
  WIDGETS_POSITION="left"

  source "$WIDGETS_DIR/spaces.sh"
}

# Centered Widgets
function center_widgets() {
  WIDGETS_POSITION="center"

  source "$WIDGETS_DIR/title.sh"
}

# Widgets on the Right
function right_widgets() {
  WIDGETS_POSITION="right"

  source "$WIDGETS_DIR/time.sh"
  source "$WIDGETS_DIR/date.sh"
  source "$WIDGETS_DIR/keyboard.sh"
  source "$WIDGETS_DIR/wifi.sh"
  source "$WIDGETS_DIR/volume.sh"
  source "$WIDGETS_DIR/battery.sh"
}

# Load Configuration with Widgets
left_widgets        && \
center_widgets      && \
right_widgets       && \
sketchybar --update 